import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from '@/Components/Header'
import { useState } from 'react'
import Todos from '@/Components/Todos'




export default function Home() {

  return (
    <>
      <Head>
        <title>TodoApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      <main className={styles.MainContainer}>
        <Header />
        <Todos />
      </main>
    </>
  )
}
